datasource:
  url: "jdbc:postgresql://localhost:5432/products"
  username: "${DATASOURCE_USER}"
  password: "${DATASOURCE_PWD}"
  connection:
    batchExecution:
      ttl: 5
  isReady: "${DATASOURCE_READY}"

